### ISSUE TITLE
Documentation incomplete - and links to Portugese pages?

### ISSUE THREAD

**Issue by Zordid** [lcarli/NodeRed-Azure-DocumentDB#1]
I have no idea how to issue a query on documents.
You just state "query like this..." but where to put the query in the msg object? No clue.
If I run without the query statement, I get an error message "Cannot read property 'replace' of undefined"

The idea is nice, but the current state is not really useful.

All your links to more information lead to Portugese pages... :-(

**Comment by Preskton** [comment]
Hi, @Zordid - same comment as the other issue. If you're still up for trying this node, the document was updated a bit to help you get going.
