### ISSUE TITLE
Node results are STRINGS, not proper objects

### ISSUE THREAD

**Issue by Zordid** [lcarli/NodeRed-Azure-DocumentDB#2]
Ok. I managed to do a query. But the Document node emits a String! 

String[258]
    Query successfully
    [{"id":"47111","orderNo":"47111","_rid":"dcIaAJrA+QADAAAAAAAAAA==","_self":"dbs/dcIaAA==/colls/dcIaAJrA+QA=/docs/dcIaAJrA+QADAAAAAAAAAA==/","_etag":"\"0000d510-0000-0000-0000-58343b8f0000\"","_attachments":"attachments/","_ts":1479818125}]

How on earth am I supposed to go on with this?
Sorry, but who is able to actually use your node like it is?

**Comment by Preskton** [comment]
Hi, @Zordid, I've corrected some of this as part of PR#6. For the `Documents` node, the result of each operation is now relays the original message and updates `msg.payload` as expected. There is also now a `msg.docdb` that contains original info about the query.

Please note that I haven't extended this to the `Documents` nor `Collections` nodes quite yet.

**Comment by Preskton** [comment]
Hi, @Zordid - @lcarli has merged PR#6, so the results are a bit nicer to work with. Hopefully 9 months later can still help out somehow! :)
