### ISSUE TITLE
Node doesn't work - connection issues

### ISSUE THREAD

**Issue by markrey** [lcarli/NodeRed-Azure-DocumentDB#3]
Thank you for creating node!
After trial, Node has few issues 

1. No global configuration ( for central URL / Key configuration )
2. Not possible to put two nodes on one flow. ( previous ones get disconnected )
3. Errors on Query

**Comment by Preskton** [comment]
Hi, @markrey - I've corrected your number two above with PR#6. Please note that I haven't gone through and fully tested the `Database`/`Collections` nodes, as I've only been using the `Documents` node.

I'm successfully using the `Documents` node for create, update, and query.

**Comment by Preskton** [comment]
Hi, @markrey - PR#6 has been merged. If you're still interested in using this node, could you please retry #2 and #3 based on the updates? I'm going to split #1 out as a new issue and close this one.
